name: Go Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3 

      - name: Install dependencies
        run: go mod tidy

      - name: Run database tests
        run: go test ./database -v

      - name: Run user handlers tests
        run: go test ./handlers -v
